- .gitignore
- Makefile.littlewire
- README.md
- RF24.cpp
- RF24.h
- RF24_config.h
Working implementation of LittleWire for RF24
> Littlewire

- RPi/bcm2835.c
- RPi/bcm2835.h
Merging the updated bcm2835.c (v 1.39) with the slightly-customized version that exists in this repository. 
It continues to work on my RPi B; I don't have my RPi 2 *yet* (Saturday!), but reports indicate the it (the v 1.39 version of bcm2835.c) works as expected on the RPi 2.
> Potential RPi 2 support via updated bcm2835.c (version 1.39)

- RPi/pyRF24/pyRF24.cpp
- RPi/pyRF24/setup.py
- examples_RPi/pingpair_dyn.py
#144
https://github.com/TMRh20/RF24Network/issues/44
Signed-off-by: root <mzfuzzy800@gmail.com>
> Python3 support added.

- Makefile
- examples_RPi/Makefile
- examples_RPi/extra/Makefile
- examples_RPi/interrupts/Makefile
Autodetect Raspberry Pi 2 with ARM7.
> RPI2 autodetection

- examples/GettingStarted/GettingStarted.ino
@Ravi0li, can you please retest if that fix works with your boards?
> Fix for #217 GettingStarted enhancement.

- examples/GettingStarted/GettingStarted.ino
Reverts TMRh20/RF24#218 per reccomendation of TMRh20.
> Revert "Fix for #217 GettingStarted enhancement."

- RF24.h
- update for makefile improvements
- python wrapper updates
- cross compilation
- duplications removed
- minor doc fixes
> Documentation update for makefile improvements etc.

- library.json
Related issues: https://github.com/TMRh20/RF24/issues/275 , https://github.com/platformio/platformio/issues/748
> Update PlatformIO library manifest

- examples/scanner/scanner.ino
- examples_linux/extra/scanner.cpp
This pull request address issue #300 and changes the code of the scanner program in ``examples_linux/extra`` to fix it's output and make it consistent with the Arduino version of the same program.
> fixed output and made it consistent with output from Ardunio version.

- utility/RPi/interrupt.c
- utility/RPi/spi.cpp
> add static initialization for pthread mutexes

- RF24.cpp
- RF24_config.h
- examples/rf24_ATTiny/timingSearch3pin/timingSearch3pin.ino
- nRF24L01.h
This change is based on the discussion from https://github.com/nRF24/RF24/issues/393
So thank @olivier-lefebvre!
> Fix build issues against ESP32 (ESP-WROOM-32).

- RF24.cpp
Useful also to solve issue #499
Change SPI0 to SPI1 Raspberry Pi 3
> Mod to run RF24 on Raspberry SPI1

- RF24.cpp
- RF24.h
This PR adds a function to get automatic retransmission count
Thanks, @kargeor!
> Add function to get automatic retransmission count

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- COMMON_ISSUES.md
- CONTRIBUTING.md
* Update link to NASA C Style Guide
* Add Issue Templates
* Create `COMMON_ISSUES.md`
> Improve Github docs

- library.json
> Fixed platforms list in library.json

- .clang-format
- .github/workflows/build_arduino.yml
- RF24.cpp
- RF24.h
- RF24_config.h
- utility/pigpio/RF24_arch_config.h
- utility/rp2/RF24_arch_config.h
> all single line loops and conditions use curly brackets

- .github/workflows/doxygen.yml
> add manual trigger to docs CI

- docs/pico_sdk.md
Hopefully this can avoid issues like #912
> Mention RPi Pico board's 3v regulator in Pico SDK doc

- COMMON_ISSUES.md
> Docs: Byte alignment/packing mismatches

- utility/pigpio/compatibility.cpp
> Fix for pigpio delayMicroseconds

- utility/RPi/interrupt.cpp
- utility/RPi/interrupt.h
- utility/SPIDEV/gpio.cpp
- utility/SPIDEV/gpio.h
- utility/SPIDEV/interrupt.cpp
in accordance with nRF24/pyRF24#48
> use quotes for linux/gpio.h include

- RF24.cpp
- examples/scanner/scanner.ino
- examples/scannerGraphic/scannerGraphic.ino
> fixes for STM32

- RF24.h
- pyRF24/pyRF24.cpp
applied to python wrapper also
I broke this out to a separate branch because my work on other branches depends on this.
> feat: publicly expose `ce()` for advanced uses.

- utility/RPi/bcm2835.c
- utility/RPi/bcm2835.h
See changes noted in bcm2835.h
> update copy of BCM2835 lib to v1.75

- RF24.cpp
This reverts commit 48005ce854e695108fe478c7c21669cde6287a35.
> Revert "Add required delay for Linux (#1034)"
