nRF24/RF24

RPi/pyRF24/pyRF24.cpp
original fix changed in order that default values are not in the wrapper anymore.
=> adapted python wrapper for RF24 interface changes in txStandBy and startFastWrite

examples/rf24_ATTiny/rf24ping85/rf24ping85.ino
The addresses are reversed when using with the GettingStarted sketch as
described in the comments. This causes the arduino and the tiny to both
be in receiver mode.
=> Address fix for attiny example sketch

RF24.cpp
- reset config register to default values on radio.begin
Some NRF24L01+ modules start-up with different config values.
- remove additional toggle_features (already called in radio.begin).
=> Some changes to get different revisions of NRF24L01+ modules working.

RF24.cpp
Found an issue regarding CSN pin with new MRAA commit: https://github.com/TMRh20/RF24/commit/3d049abfe890225bb8232f2a025e7415e731e6e2
in ```RF24::csn(bool mode)``` ```#ifdef ARDUINO``` block is now not closed with ```#endif``` so that ```#elif !defined (ARDUINO_SAM_DUE)``` never get's compiled, and actual digitalWrite is issued.
This works with MRAA builds, because ```ARDUINO``` is not defined there. Feeling myself useless, as I spent half a day with scope trying to figure out what's happened to my galileo, while problem was on the other side :)
Also, shouldn't ```SPI::setBitDataOrder``` and other SPI related functions (except for ```chipSelect``` for RPi perhaps) be issued in ```RF24::begin```?
=> Fixed issue with ARDUINO not issuing CS for radio

RF24.cpp, RF24.h, RF24_config.h, arch/MRAA/RF24_arch_config.h, arch/MRAA/compatibility.c, arch/MRAA/compatibility.h, arch/MRAA/gpio.cpp, arch/MRAA/gpio.h, arch/MRAA/includes.h, arch/MRAA/spi.cpp, arch/MRAA/spi.h
I've made some updates to ```GPIO``` and ```SPI``` classes, so they destruct correctly. Also, an empty virtual destructor must be added to ```RF24``` so it will be called, and call destructors for all "full" members (eg not pointers).
I've tryed to add code that will set SPI parameters to ```RF24::csn```, but it resulted in heavy perfomance drop, due to MRAA constantly writing to syslog of incorrect SPI parameters, like changing 8MHz into 5MHz on my Galileo board.
I've added required defines into MRAA/RF24_arch_config.h so you can add ```|| defined(MRAA)``` in ```RF24::csn``` to test it yourself.
In RF24_config.h I've changed defined(MRAA) into defined(RF24_MRAA), as MRAA can only be defined in compile options, or in "arch/includes.h", also it's RF24_MRAA referred later in comments, so I …
=> MRAA: Updated memory usage

RF24.cpp
In C, logical not (!) has precedence over bitwise and (&). The current code will yield the wrong result in the following case:
RX_EMPTY bit is unset, meaning packet is present.
Some other FIFO_STATUS bit is set, giving the register as a whole a non-zero value.
! non-zero value = 0
0 & _BV(RX_EMPTY) = 0
So even though a packet is present, false is returned. The correct implementation can be seen in the available() function.
=> Fix operator precedence for isAckPayloadAvailable.

RF24.cpp, RF24_config.h
Added support for ATtiny2313 and ATtiny 4313 MCUs. Tested with google-code arduino-tiny core.
As for second change - slave select logic is implemented in main RF24 class with `csn()` function, using hardcoded SS pins in SPI class is not needed. Furthermore, calling `radio.begin()` will set SS pin OUTPUT and HIGH even in 3 pin mode, and it will overwrite any state set by user or another library configured to use this pin.
=> ATtiny2313/4313 support, ATtiny 3 pin mode fix

RF24.h
This finishes Tiny2313/4313 support by adding pin configuration documentation. Also fixed some incorrect pin names and numbers in other ATtinys doc.
=> Fixed inconsistent documentation, added Tinyx313 pin map

Makefile, examples_RPi/Makefile, examples_RPi/transfer_interrupt.cpp, utility/RPi/includes.h, utility/RPi/interrupt.c, utility/RPi/interrupt.h
=> Using interrupts on RPi

examples/GettingStarted/GettingStarted.ino
The GettingStarted sample is apparently intended to send a number from the transmitter
to the receiver and echo that same number back again, but the code wasn't outputting
the echoed number properly. Now it doesn, and the user can see that the same number was
sent and echoed back.
=> Fix GettingStarted sample

RF24.cpp
This change fixes the following compiler warning I get when building
on Arduino IDE version 1.6.7
"/var/folders/sv/27zk61c9449f9wycpfhq9dmr0000gn/T/build68a338274e8c0af55d2a1e6113ec3df2.tmp/libraries/RF24/RF24.cpp.o"
/Users/flaviof/Documents/Arduino/libraries/RF24/RF24.cpp:559:17: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
printf_P(PSTR("Data Rate\t = "PRIPSTR"\r\n"),pgm_read_word(&rf24_datarate_e_str_P[getDataRate()]));
^
/Users/flaviof/Documents/Arduino/libraries/RF24/RF24.cpp:560:17: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
printf_P(PSTR("Model\t\t = "PRIPSTR"\r\n"),pgm_read_word(&rf24_model_e_str_P[isPVariant()]));
^ …
=> Fix warning: C++11 requires a space between literal and identifier

RF24.cpp
maskIRQ was buggy. The interrupts bits were only being ORed. They need to be AND cleared first.
=> maskIRQ: Fixed function to clear interrupt bits first.

Doxyfile, RF24.h
When trying to follow the documentation I noticed that the old folder names were being used.
=> Change examples_RPi to examples_linux

RF24.h, RF24_config.h
I have change the detection scheme in order to correctly detect the Atmel Studio 7 ATXMega256D3 MCU.
Because in windows would take extra steps to use the configure in order to put the correct include.h files, I change the order of detecting the MCU.
The other way is to put the needed changes in configure file and call it from windows command prompt (and in linux too) before any other action meaning that users have to install additional software.
=> Changes in RF24_config.h prohibits the detection of XMEGA.

RF24.h
getCRCLength() returns RF24_CRC_DISABLED, not RF24_DISABLED... which explains the "RF24_DISABLED not defined" error I was getting ;)
=> Minor documentation correction - RF24_CRC_DISABLED

RF24.cpp
Hi,
I'm using this library for automated benchmarks and energy measurements, which means that I frequently call begin() to re-set the nRF24 chip to its defaults and start a new measurement with different parameters. I noticed that begin() initializes the hardware with dynamic payloads disabled, but does not set the corresponding variable, which means that it can remain true if dynamic payloads were previously enabled (even though the call to begin() disables them).
Calling begin() more than once probably isn't the inteded usage, but just in case someone else also does this, this commit should help them.
=> RF24::begin: reset dynamic_payloads_enabled to false

examples/scanner/scanner.ino
The desired functionality is to display all channel measurements greater than 0xF as 0xF. The current behavior picks the minimum between `0xF` and `(value & 0xF)`, which is just the last hex digit of the measurement.
If the value was `0x12`, the code would print `2` rather than `F`. This change just makes `min` compare `0xF` with the full value of the measurement, such that measurements above `0xF` will always get clamped correctly.
=> Fix clamping to a single hex digit

utility/SPIDEV/spi.cpp, utility/SPIDEV/spi.h
fix several errors:
struct spi_ioc_transfer tr; was not initialized to zero.
initializer did not set the proper members.
cs_change = 0 causes incorrect csn behaviour.
using namespace std; can cause name conflicts in client code.
=> fix SPIDEV interface

RF24.cpp, RF24.h
When SETUP_AW contains a value 1 or 2 or 3 then it is ok (according to the specification). I have hardcoded those values in the "if" condition. I could expose a new bit mnemonics for SETUP_AW (however mnemonic AW already exist) and use that _BV macro? I do not know which is better.
=> Proposing a fix for #272.

RF24.h
Since flush_rx was removed from startListening, this provides an option
to flush the RX buffer in use cases where this is required.
Related to issue #323
=> Make flush_rx public

configure
On a Raspberry 2 B+ with Raspberian Jessie the configure faild detecting the soc.
/proc/cpuinfo returns BCM2835 as Hardware, add this code to the soc and driver mapping.
=> Fix configure for Raspberry PI 2 B+ Raspberian Jessie

Makefile, configure, utility/wiringPi/RF24_arch_config.h, utility/wiringPi/includes.h, utility/wiringPi/spi.cpp, utility/wiringPi/spi.h
In case the wiringPi and the RF24 are used together in the same
application CPU load goes to 100%. The solution was to create a new
implementation based on the SPI from wiringPi library. In order to
have it working the wiringPi library should be already installed.
For enabling this implementation the "--driver=wiringPi" should be
considered when compiling the RF24.
Fixes the reported issues from #305 ticket.
Signed-off-by: Aurelian Z. <aurelian17@gmail.com>
=> Added implementation for wiringPi driver

RF24_config.h
Not sure exactly when PROGMEM support was added to ESP8266 Arduino, but all of the necessary features are available:
http://esp8266.github.io/Arduino/versions/2.0.0-rc2/doc/reference.html#progmem
This PR removes the macro overrides that disable PROGMEM for ESP8266. I found that  `PRIPSTR` was still necessary.
Without this, pulling the RF24 library into an ESP8266 project clobbers the ability to use PROGMEM reliably.
=> Remove progmem macro overrides for ESP8266 (ESP8266 Arduino now supports them)

RF24.h, RF24_config.h
This pull request is a solution for #369 
*Example project to test*
platformio.ini
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
https://github.com/trojanc/RF24.git#069a4f491347f3e6963da92118fb44a950a1699f
DigitalIO@1.0.0
build_flags = -DSOFTSPI -DSOFT_SPI_SCK_PIN=9 -DSOFT_SPI_MOSI_PIN=7 -DSOFT_SPI_MISO_PIN=8
```
app.cpp
```c++
#include <Arduino.h>
#include <SPI.h>
#include "DigitalIO.h"
#include "RF24.h"
#include "printf.h"
RF24 radio(5, 6);
void setup(){
Serial.begin(115200);
printf_begin();
radio.begin();
radio.printDetails();
}
void loop(){
}
```
_also add printf.h from library to source directory_
Using this fix you can install the library and configure the soft spi pins without having to change source code of the library
=> Fix for #369

utility/SPIDEV/RF24_arch_config.h, utility/SPIDEV/spi.cpp, utility/SPIDEV/spi.h
Remove perror+abort (error handling) in SPIDEV driver. This solve the
problem of abort called in the library that will be terminate the
process.
a try{…} catch(SPIException &e) {} will permit consistent error
handling for library users.
This will address the following suggestion in #407 :
> Abuse of perror + abort(): Abort will stop the running process, this is not good practice for a library. A library should report the error to running process so it can be handled. As the library is C++ perror+abort should be subtitured by custom exception that can be cached by library user.
=> Change perror/abort in SPIDEV driver c++ std exception

utility/RPi/bcm2835.c
Previously when compiling with the bcm2835/RPi driver gcc would emit the following warnings:
utility/RPi/bcm2835.c: In function ‘bcm2835_gpio_pad’:
utility/RPi/bcm2835.c:420:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (bcm2835_pads == MAP_FAILED)
^~
utility/RPi/bcm2835.c:423:5: note: ...this statement, but the latter is misleadingly indented as if it is 
guarded by the ‘if’
volatile uint32_t* paddr = bcm2835_pads + BCM2835_PADS_GPIO_0_27/4 + group;
^~~~~~~~
utility/RPi/bcm2835.c: In function ‘bcm2835_gpio_set_pad’:
utility/RPi/bcm2835.c:433:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (bcm2835_pads == MAP_FAILED)
^~
utility/RPi/bcm2835.c:436:5: note: ...this statement, but the latter is misleadingly indented as if it is …
=> Fixed misleading indent warning in bcm2835.c

utility/SPIDEV/compatibility.c, utility/SPIDEV/compatibility.h, utility/SPIDEV/gpio.cpp, utility/SPIDEV/gpio.h
Improve the SPIDEV compatibility layer:
- Solve #454 that breaks millis() functions.
- Improve delay,delayMicros & millis() using clock_* functions vs nanosleep/getimeofday that are considered deprecated or not safe.
- Address issue #407 for GPIO error management avoiding exit/abort calling in favor of specific exception that can be controlled by the calling program.
- Improve GPIO speed caching sysfs files and using system calls to reduce FILE* overhead. GPIO switching will be faster.
This PR has been tested in 32bit & 64bit envirments
=> SPIDEV compatibility layer improvement and patch for 64bits

RF24.cpp
Before this change the divider is always 2 which violates the
nRF24L01 timing requirements for clock frequencies > 20MHz.
Now a suitable divider is chosen automatically to keep the
SPI clock frequency in the range 5 MHz - 10MHz.
This change is required for STM32F103 boards which run at 72MHz by default. Everything else works out of the box => closes #462.
=> Automatically choose correct SPI clock divider.

RF24.cpp
I wanted to use this library with PlatformIO for my attiny84 project.
It didn't work but i discovered that the cause was a different pin definition for the pinMode functions.
This patch uses the DDRx registry and makes the code independent of the different pin definitions.
=> make attiny SPI code independent from different Arduino pins definitions

configure
Cross-compiling using arm-linux-gnueabihf-gcc 7.4.0 resulted in the following error:
```
sorry, unimplemented: Thumb-1 hard-float VFP ABI
```
It seems that using `-march=armv6` or `-march=armv6zk` with armhf results in
this error, while it works fine with `-marm` .
=> Update -march definition on RPi (BCM2835)

.github/workflows/build_linux.yml
This configures GitHub Actions to build for:
- BCM2835 (w/ drivers RPi and wiringPi)
- BCM2836 (w/ driver RPi)
I had to hopefully temporarily rely on a personal fork of https://github.com/WiringPi/WiringPi to make it cross-compilable. At the moment it doesn't allow CC to be externally defined, and it is set to `gcc`, so it's not possible to build from x86-64 to armhf for instance.
It should be relatively easy to add builds for other Linux platforms, and possibly Arduino too.
=> Add GitHub actions configuration

utility/RPi/spi.cpp
It appears that on Raspberry Pi, the code checks
that the process is running as root.
When it's not, it throws a very cryptic error (see #531):
terminate called after throwing an instance of 'int'
I'm not sure that making it compulsory to run as root
is justified, but at least this change improves the
error message.
After it appears as:
terminate called after throwing an instance of 'std::runtime_error'
what():  Process should run as root
=> [RPi] Improve exception when not running as root

utility/SPIDEV/spi.cpp, utility/SPIDEV/spi.h
When creating multiple instances of SPI class using SPIDEV driver,
only the first one got initated, because spiIsInitiated was defined as
global variable. It was changed to be a private variable of SPI class.
=> Fix for creating multiple instances with SPIDEV

RF24.cpp
Hello,
this pull request prevents an undefined behavior when calling openReadingPipe() with child == 6 caused by accessing element 6 of the array child_pipe.
=> Fixed undefined behavior on openReadingPipe

CONTRIBUTING.md, README.md
I made the docs link stick out more, so it would be harder to miss. Also appended a link to the contributing guidelines.
contributing guidelines now have embedded links for PEP8 and Arduino style guides, This should be more definitive then letting google determine what we mean.
=> links in CONTRIBUTING append link to CONTRIBUTING in README

CONTRIBUTING.md
starting to get doxygen now. But the official reference manual seems a little vague. e.g. I can't find where the "@" (like `@param`) commands are explained/listed.
added link to "documenting the code section" to steer prospective contributors in the official direction.
=> embed doxygen link in CONTRIBUTING.md

RF24.cpp
I _think_ this addresses #629, can it really be that simple?
(Tested on Raspberry Pi Zero-W.)
=> add ARC to printDetails()

RF24.cpp
I've rearranged the suggested code slightly. Seems to work OK.
Tested between Uno and Pro Mini using the pingpair_ack sketch.
=> available() could be slightly faster #631

RF24.cpp, RF24.h, RF24_config.h
(This relates to #683 )
@2bndy5 if you have any further timings which could be usefully configured in this way, please ask!
(Also, apologies for all the commit noise below: hopefully git is smart enough to throw it away.)
=> Make RF24_POWERUP_DELAY configurable in RF24_config.h

RF24.h, examples/GettingStarted/GettingStarted.ino, examples_linux/acknowledgementPayloads.cpp, examples_linux/gettingstarted.cpp, examples_linux/interruptConfigure.cpp, examples_linux/manualAcknowledgements.cpp
since I rewrote all the linux examples I noticed the install instructions for the python wrapper direct the user to edit/run an example that no longer exists.
This is a quick fix for just that. (changes tested/rendered correctly on my local machine)
=> follow-up fixes from #691

RF24.h
Now that the datasheets exist on this repo, I noticed the links to datasheets on docs' main page don't work. 
This PR mimics original behavior exhibited by tmrh20.github.io repo
=> fix links to datasheets

RF24.cpp, RF24.h
Fixes #706 and closes #716. Both fixes in this PR resolves errors noticed by @combs & @DrClaudio73
1. Use binary representation to show the auto-ack feature when configuration differs per pipe
2. Uses correct mnemonic to output "primary mode"
Tested changes using python wrapper; it works as expected.
=> Fix print pretty

.github/workflows/build_linux.yml, RF24.cpp
This PR fixes a couple changes I made in #691 that seemed to upset community members concerning backward compatibility. 
1. open pipes 0 & 1 in `begin()`noticed in #734
2. `enableAckPayloads()` also enables dynamic payloads for pipe 1 automatically. Reddit and Arduino forum users have gotten quite upset about this one (to which my reaction has been "RTFD" or "pay more attention to examples' comments").
Also, I'm disabling the WiringPi CI build to discontinue "Linux build CI failed" notifications that I keep getting. I've successfully built WiringPi locally on my RPi2 (and subsequently RF24 built successfully) using upstream WiringPi repo... I think that libcrypt.so.1 is not available for cross-compilation on x86 Ubuntu, but it seems to ship with armhf-based OSs (like Raspberry Pi OS). …
=> Community appreciation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md
This updates the prompt by directing users to read the COMMON_ISSUES.md file in the "Bug Report" template. Also I added the same prompt to the "Question" template as many of the question-labeled issues could be avoided by also reading it, but most humble people don't think their questions are bug-related.
=> endorse COMMON_ISSUES.md in issue templates

examples_pico/multiceiverDemo.cpp
At least my gcc 10 showed some compiler warnings regarding printf format specifiers. This PR fixes them.
=> Fix compiler warnings

docs/pico_sdk.md
The howto document is very well written and clear. I did some smaller modifications to it :)
=> Minor changes in the rp2xx howto document

RF24.cpp, RF24_config.h, examples/AcknowledgementPayloads/AcknowledgementPayloads.ino, examples/MulticeiverDemo/MulticeiverDemo.ino, examples_linux/acknowledgementPayloads.cpp, examples_linux/acknowledgement_payloads.py, examples_linux/getting_started.py, examples_linux/manual_acknowledgements.py, examples_linux/multiceiverDemo.cpp, examples_linux/multiceiver_demo.py, examples_linux/streaming_data.py, library.json, library.properties, utility/RPi/RF24_arch_config.h
~I missed a define that was supposed to be removed when testing the overload-begin() branch.~
EDIT: see https://github.com/nRF24/RF24/pull/771#pullrequestreview-673748544 comment below
Thanks to @bifferos for noticing this in #770
=> undo latest changes to SoftSPI & add patches

docs/pico_sdk.md
Changed SPI custom pins example in pico_sdk.md, couldn't get it working without use of SPI spi_ then using spi_ to pass into radio.begin(), updated comments to better reflect pin orders.
=> [pico_sdk.md] improve SPI custom pins example snippet

RF24.h
I noticed this while reading the docs. Figured I'd submit a PR since it's on GitHub.
=> fix recieved -> received  typos

COMMON_ISSUES.md
Just based upon experience of these modules. 
Good PSU is everything (preferably alongside a low ESR cap)!
Using 2x Arduino Nanos (non-genuine) 2x NRF24+PA+LNA had same issue with lost packets, both better when touched, fixed by external 3.3v power source.
Using 2x identical PCB boards and Pico shows that a low ESR rated capacitor RX packets per second go from ~5 to ~100
Hope this helps people, these modules are great, when they work! :)
=> Updated common issues added issues and fixes

.github/workflows/build_arduino.yml, .github/workflows/build_linux.yml, .github/workflows/build_platformIO.yml, RF24.cpp, RF24.h, RF24_config.h, examples/GettingStarted/GettingStarted.ino, pyRF24/pyRF24.cpp
now you can use your RF24 object to format a buffer with debugging information
=> add support for sprintf

.github/workflows/build_linux.yml, Makefile, configure, docs/linux_install.md, docs/using_cmake.md, examples_linux/Makefile
solves #834
Using the RPi OS lite image doesn't ship with pigpio, and the configure script wasn't properly detecting if pigpio is installed.
- adjust configure script to check for pigpio in
1. user installed location (when fetched from git src - typically in /usr/local/lib)
2. apt installed location (typically in /usr/lib)
3. and /usr/arm-linux-gnueabihf (for 32bit cross-compiling purposes)
- adjust Makefile for lib and linux examples
- augment install docs with info about pigpio as req for IRQ (and remind reader that RPi OS lite doesn't come with pigpio).
I tested this with the Linux CI: When using the SPIDEV driver (with the configure script), pigpio is no longer installed.
=> Patch for #834

printf.h
Pull request opened from issue #842. 
This includes the megaAVR architecture into printf.h to allow radio.printDetails(); to work with Nano Every.
=> Update printf.h to include megaAVR

docs/sphinx/conf.py
A slight refactor in latest sphinx-immaterial theme release requires a change in the specified extensions. Specifically the extension that automatically links certain datatypes (like `uint8_t`) to cppreferences,com.
=> respect latest sphinx theme ext refactoring

RF24.cpp
This was an oversight on my behalf when first writing the function. Thanks to @stefan123t for bringing this to my attention.
=> add model variant info to printPrettyDetails()

examples_linux/acknowledgement_payloads.py, examples_linux/getting_started.py, examples_linux/interrupt_configure.py, examples_linux/manual_acknowledgements.py, examples_linux/multiceiver_demo.py, examples_linux/scanner.py, examples_linux/streaming_data.py
These are improvements to the python examples that I found useful when testing nRF24/pyRF24#9
I also added the scanner example from https://github.com/nRF24/RF24/issues/714#issuecomment-949665412 
These changes may not be python 2 compatible. Not really sure if that's a problem because RPi OS no longer ships with python2. I'm more concerned with people that haven't updated their RPi's OS image in over a year.
=> Update py examples

docs/pico_sdk.md
The RP2040, Pico SDK and the Pico documentation are all produced by Raspberry Pi ( https://www.raspberrypi.com/ ) and not by Raspberry Pi Foundation ( https://www.raspberrypi.org/ )
=> Fix Raspberry Pi company name

utility/CMakeLists.txt
This is needed to update the pyRF24 pkg to use latest master.
This should not negatively affect RF24 lib builds because RF24_NO_INTERRUPT is respected in the root CMakeLists.txt. But, the pyRF24 pkg doesn't actually use the root CMakeLists.txt. Instead, the pyRF24 pkg only uses utility/CMakeLists.txt to get the appropriate driver sources/includes/etc.
This is the CMake equivalent of #839 which did the same exclusion of interrupt.h when it wasn't needed.
=> make utilities/CMakeLists.txt respect RF24_NO_IRQ

RF24.cpp, RF24.h
Also amends an outdated comment in the definition.
New doc output:
Related to user experience described in #865
=> adjust writeFast docs

RF24_config.h, utility/LittleWire/RF24_arch_config.h, utility/MRAA/RF24_arch_config.h, utility/RPi/RF24_arch_config.h, utility/SPIDEV/RF24_arch_config.h, utility/pigpio/RF24_arch_config.h, utility/rp2/RF24_arch_config.h, utility/wiringPi/RF24_arch_config.h
Calling this macro caused the following error:
> 'const void*' is not a pointer-to-object type
Similar macros, like `pgm_read_word()` and `pgm_read_byte()` are also incorrect; I can open a second PR for them if you need.
Fixes https://github.com/bblanchon/ArduinoJson/issues/1790
=> Fix `pgm_read_ptr()`: 'const void*' is not a pointer-to-object type

.github/workflows/build_arduino.yml, .github/workflows/build_linux.yml, .github/workflows/build_platformIO.yml, RF24_config.h, utility/ATXMegaD3/RF24_arch_config.h, utility/LittleWire/RF24_arch_config.h, utility/MRAA/RF24_arch_config.h, utility/RPi/RF24_arch_config.h, utility/SPIDEV/RF24_arch_config.h, utility/Template/RF24_arch_config.h, utility/pigpio/RF24_arch_config.h, utility/rp2/RF24_arch_config.h, utility/wiringPi/RF24_arch_config.h
Corresponding to https://github.com/nRF24/RF24/pull/864, this completes compliance with the unified ArduinoCore-API about 
- `pgm_read_word()`
- `pgm_read_byte()`
see https://github.com/arduino/ArduinoCore-API/blob/e26862e453c1234e1c23506d1839bfa68999d911/api/deprecated-avr-comp/avr/pgmspace.h#L102-L103
- adds RP2040 boards to Arduino CI, namely
- RPi pico
- RPi pico W
- Adafruit Feather RP2040
- Arduino Nano Connect (RP2040)
- adds STM32 boards to PlatformIO CI, namely
- STM32F103C8 (blue pill)
- STM32F411CE (black pill)
- installs cpp-linter pkg from PyPI instead of building it from github source
---
Special thanks to @bblanchon for bringing this to our attention and providing a comprehensive list of affected cores.
=> Fix `pgm_read_byte/word()` definitions

.github/workflows/build_platformIO.yml, RF24_config.h
resolves #870
I also added the 2 boards to the PlatformIO CI workflow:
1. Node MCU ESP8266 board
2. Adafruit QtPy ESP32-S2 board
This should help us detect compiler warnings and whatnot.
=> add printf support to ESP32/8266 and arduino-pico cores

docs/pico_sdk.md
Hi,
Updated some of my code that uses the RF24 library, guess there's been some changes in the meantime as the previous code no longer compiles. Quick look suggests now the SPI needs be declared seperately and cannot be reference just by importing RF24 and using spi.begin
Previous code:
```
spi.begin(spi_bus, sck_pin, tx_pin, rx_pin);
if(radio.begin(&spi, ce_pin, csn_pin) == false) {     // Setup and configure rf radio
return(false);
}
```
Seems to be fixed by declaring a SPI object outside the function that initialises the radio. (could be a better way to do this?)
`SPI spi;`
Hence have suggested a change to documentation to reflect this.
=> Update pico_sdk.md to reflect changes to SPI with user-specified pins

COMMON_ISSUES.md
- Update comment regarding troubleshooting and CE Pin
- Add info on the different write() functions
#816 
closes #877
=> Update COMMON_ISSUES re: write() function

utility/MRAA/compatibility.cpp, utility/MRAA/compatibility.h
- Found MRAA timer functions not working properly
- Copy timing functions from SPIDEV
=> Update MRAA timer functions

docs/main_page.md
- Add link and info for nrf_to_nrf
- Modify datasheet link to just one link
=> Modify Main docs page

utility/MRAA/compatibility.cpp, utility/MRAA/compatibility.h, utility/SPIDEV/compatibility.cpp
Small but important fix for SPIDEV & MRAA: delayMicroseconds() per @2bndy5 in #950
=> Fix for SPIDEV & MRAA: delayMicroseconds()

examples/ManualAcknowledgements/ManualAcknowledgements.ino
Closes #949
- Add delay to relax how often available() is called to let the radio internally do its thing
- Thanks to @pfpp89 for discovering, reporting & testing this issue
=> Add delay to manualAcknowledgements example

docs/linux_install.md
- Point to new CMake installer by default
- Mark old installer deprecated
I think this change will make things easier for users, since the CMake installer works on every RPi version.
I've marked the old installer 'Deprecated' as well
=> Link to new (CMake) installer by default

examples/InterruptConfigure/InterruptConfigure.ino, examples_linux/interruptConfigure.cpp, examples_pico/interruptConfigure.cpp
closes #939 
This basically just moves most of the ISR logic into main loop to relieve the MCU from overperforming in IRQ events.
=> separate ISR handling from IRQ processing

CMakeLists.txt, utility/SPIDEV/RF24_arch_config.h, utility/SPIDEV/gpio.cpp, utility/SPIDEV/gpio.h
- uses Linux Kernel's Character Device v2 ABI instead of the deprecated v1 ABI
- caches the File Descriptors used to control GPIO pins
=> Update SPIDEV driver for Character Device v2 ABI; cache FDs

utility/RPi/interrupt.cpp, utility/RPi/interrupt.h, utility/SPIDEV/gpio.cpp, utility/SPIDEV/gpio.h, utility/SPIDEV/interrupt.cpp
This will prevent falling back to `/dev/gpiochip0` when `/dev/gpiochipX` was previously opened successfully.
This is designed to alert users when multiple processes are simultaneously using `/dev/gpiochipX`, but it should only happen if either
1. another process is spamming the gpiochipX.
2. the rare occurrence when RF24 needs to open gpiochipX while it is still used by another process.
=> cache gpio chip detection when properly initialized

docs/main_page.md
- Recently added some changes to the RF24G lib to support nrf52x devices, and up to 7 devices in a 'true mesh' configuration where every device has a path to every other device. Kind of a neat library, clean and straightforward.
- https://github.com/Hobietime/RF24G/pull/5
=> Add link to RF24G library in docs

RF24.cpp, RF24.h, utility/MRAA/RF24_arch_config.h, utility/MRAA/gpio.cpp, utility/MRAA/gpio.h
=> revise MRAA driver's GPIO implementation

.github/workflows/doxygen.yml, docs/Doxyfile, docs/doxygen-custom.css, docs/python_wrapper.md, examples_linux/acknowledgementPayloads.cpp, examples_linux/acknowledgement_payloads.py, examples_linux/getting_started.py, examples_linux/gettingstarted.cpp, examples_linux/interruptConfigure.cpp, examples_linux/interrupt_configure.py, examples_linux/interrupts/transfer_interrupt.cpp, examples_linux/manualAcknowledgements.cpp, examples_linux/manual_acknowledgements.py, examples_linux/multiceiverDemo.cpp, examples_linux/multiceiver_demo.py, examples_linux/ncurses/scanner_curses.cpp, examples_linux/scanner.cpp, examples_linux/scanner.py, examples_linux/streamingData.cpp, examples_linux/streaming_data.py, pyRF24/pyRF24.cpp
- expose selected `RF24_DRIVER` in the python wrapper (for programmatically specifying the right pins)
- update for the python examples
- interrupt_configure.py uses gpiod instead of RPi.GPIO
- removed argparse from examples for simplicity
- use the appropriate pin numbers for the selected `RF24_DRIVER`
- revised the python wrapper's install doc
=> update python wrapper/examples/doc

Makefile, examples_linux/CMakeLists.txt, examples_linux/Makefile, examples_linux/interruptConfigure.cpp, utility/CMakeLists.txt, utility/MRAA/gpio.cpp, utility/MRAA/includes.h, utility/MRAA/interrupt.cpp, utility/MRAA/interrupt.h, utility/MRAA/spi.cpp, utility/MRAA/spi.h
I also removed MRAA exclusion from examples build. Previously, interruptConfigure.cpp was not built for MRAA driver.
=> wrap MRAA lib's `Gpio::isr()` for IRQ support

examples_linux/CMakeLists.txt, utility/RPi/interrupt.cpp, utility/RPi/interrupt.h
Just does what the title says, instead of using the Linux Kernel.
=> Use BCM2835 lib's Edge Detection Status for IRQ support

utility/wiringPi/interrupt.h
I think I found the equivalent to `detachInterrupt()` in wiringPi lib. Its not documented, but [`wiringPiISRStop()`](https://github.com/WiringPi/WiringPi/blob/61126f0af04c2281240273b0f77f90fbedd8cf30/wiringPi/wiringPi.c#L2254-L2256) is used [in wiringPi lib's examples/tests](https://github.com/WiringPi/WiringPi/blob/master/examples/isr3.c).
=> wrap `wiringPiISRStop()` in driver API

CMakeLists.txt, RF24.cpp, RF24_config.h, utility/ATTiny/RF24_arch_config.h, utility/ATXMegaD3/RF24_arch_config.h, utility/LittleWire/RF24_arch_config.h, utility/MRAA/RF24_arch_config.h, utility/RPi/RF24_arch_config.h, utility/SPIDEV/RF24_arch_config.h, utility/Teensy/RF24_arch_config.h, utility/Template/RF24_arch_config.h, utility/pigpio/RF24_arch_config.h, utility/rp2/RF24_arch_config.h, utility/wiringPi/RF24_arch_config.h
=> Change SERIAL_DEBUG into RF24_DEBUG

.github/workflows/doxygen.yml, docs/doxygen-custom.css
This also upgrades to doxygen to v1.11.0 which now supports [github-style admonitions](https://www.doxygen.nl/manual/markdown.html#mddox_github_alerts).
Basically, we can write the following in markdown:
```markdown
> [!note]
> is translated to `\note`
> [!warning]
> is translated to `\warning`
> [!tip]
> is translated to `\remark`
> [!caution]
> is translated to `\attention`
> [!important]
> is translated to `\important`
```
and it will render in doxygen and github as admonitions:
> [!note]
> is translated to `\note`
> [!warning]
> is translated to `\warning`
> [!tip]
> is translated to `\remark`
> [!caution]
> is translated to `\attention`
> [!important]
> is translated to `\important`
However, these special blockquotes are root-level syntax only. Meaning you cannot nest these …
=> Update doxygen CSS

COMMON_ISSUES.md
This should draw more attention to the data misalignment answer while still hinting that it could happen if SPI speed is too high.
Just trying to follow KISS (Keep It Super Simple) convention.
=> Separate 2 problems' answers in COMMON_ISSUES.md

RF24.cpp
=> remove useless `ce()` call

.clang-tidy, CMakeLists.txt, RF24.cpp, RF24.h, RF24_config.h, examples_linux/CMakeLists.txt, examples_pico/CMakeLists.txt, printf.h, pyRF24/pyRF24.cpp
I ran this lib through clang-tidy (with a basic/non-restrictive config -- see added .clang-tidy file) and found some linting errors...
- enable generation of compilation database for all CMake builds
- add .clang-tidy config file
- resolve implicit casting cases
- resolve `else` after `return` cases
- ignore false-positive about "memory allocated with zero size"
Clang-tidy heavily depends on having a compilation database to understand how the sources are compiled. The compilation database is basically a JSON file that stores all compiler commands for each file.
A compilation database is specific to the compilation target. To check the Pico SDK examples we'd need to run clang-tidy with different parameters (the `-p=build` option).
Currently, we're using my side-project called cpp-linter to …
=> fix some linting errors noted by clang-tidy

RF24.cpp
=> init `failureDetected`

RF24.cpp, RF24.h, pyRF24/pyRF24.cpp
I got this idea from developing rf24-rs project.
This has the advantage of accurately describing a FIFO's state (including data corruption over SPI) when using `RF24::isFifo()`.
I also deprecated the overloaded `RF24::isFifo(bool about_tx, bool check_empty)` because the data returned could be considered inaccurate.
=> use enum to return precise FIFO state

RF24.cpp, RF24_config.h
I've been code golfing in rust again (on rf24-rs)...
By making `available(pipe)` call `available(void)`, we can get the same behavior without instantiating a dummy byte (`RF24_FETCH_NO_PIPE`) . This way `available(pipe)` also doesn't need to check the `pipe` parameter's value; it just mutates it because that is the overload's purpose.
This should decrease the compile size in general, more for any app that doesn't actually call `available(pipe)`.
=> fix: make `available(pipe)` depend on `available(void)`

RF24.h, cspell.config.yaml, docs/Doxyfile, docs/linux_install.md, docs/rpi_general.md, utility/RPi/RF24_arch_config.h, utility/SPIDEV/gpio.cpp, utility/SPIDEV/gpio.h, utility/SPIDEV/interrupt.cpp
resolves #1017
This also adds some info to the docs that was requested in #1017
=> refactor: set `/dev/gpiochip0` as default

utility/SPIDEV/gpio.h
I missed this in #1018 
no actual code changes. just a comment change.
=> Update doc comment for default linux gpiochip

RF24.cpp
- The rx buffer also needs to be flushed if R_RX_PL_WID returns 0
- No need for the delay
https://github.com/nRF24/RF24Network/pull/249
=> Fix for Dynamic Payloads

utility/SPIDEV/gpio.cpp, utility/SPIDEV/gpio.h, utility/SPIDEV/interrupt.cpp, utility/SPIDEV/interrupt.h
=> [Linux]: use shared pin FD cache

.github/workflows/doxygen.yml, .readthedocs.yaml, RF24.cpp, RF24.h, docs/migration.md, examples/AcknowledgementPayloads/AcknowledgementPayloads.ino, examples/GettingStarted/GettingStarted.ino, examples/InterruptConfigure/InterruptConfigure.ino, examples/ManualAcknowledgements/ManualAcknowledgements.ino, examples/MulticeiverDemo/MulticeiverDemo.ino, examples/StreamingData/StreamingData.ino, examples_linux/acknowledgementPayloads.cpp, examples_linux/acknowledgement_payloads.py, examples_linux/getting_started.py, examples_linux/gettingstarted.cpp, examples_linux/interruptConfigure.cpp, examples_linux/interrupt_configure.py, examples_linux/manualAcknowledgements.cpp, examples_linux/manual_acknowledgements.py, examples_linux/multiceiverDemo.cpp, examples_linux/multiceiver_demo.py, examples_linux/streamingData.cpp, examples_linux/streaming_data.py, examples_pico/acknowledgementPayloads.cpp, examples_pico/gettingStarted.cpp, examples_pico/interruptConfigure.cpp, examples_pico/manualAcknowledgements.cpp, examples_pico/multiceiverDemo.cpp, examples_pico/streamingData.cpp, pyRF24/pyRF24.cpp
`stopListening()` now writes the TX address to pipe 0 (for reading and writing). This deprecates the need for `openWritingPipe()` by offering an overloaded `stopListening(txAddress)`.
All examples (and the python wrapper) have been updated to use the new public `stopListening(txAddress)` accordingly.
> [!important]
> RF24Network should be updated to use the new `stopListening(txAddress)` also. This approach should retain current performance in networking layers while still satisfying #1028.
The main take away is no duplicate SPI transactions when switching to TX mode and (re)setting the TX address. This aims to fix the performance regression in #1029.
=> refactor: migrate to `stopListening(txAddress)` from `openWritingPipe()`

cspell.config.yaml, nurfile
This is completely optional. It allows simplifying (local) dev workflow by using [nushell] (isolated) as a task runner via nur.
[nushell]: https://www.nushell.sh/
[nur]: https://nur-taskrunner.github.io/docs/quickstart.html
[nur] needs to be installed locally. 
> [!note]
> [nushell] is compiled as the backend implementation of [nur].
> Therefore, [nushell] does not need to be installed.
It is easier to just install `nur` from [the github release assets](https://github.com/nur-taskrunner/nur/releases).
Unfortunately, `nur` needs to be built from it's rust sources.
1. Install rust with [rustup](rustup.rs) and follow the prompts. If installing on a RPi, then I recommend selecting a "minimal" install configuration (instead of the "default" configuration) to avoid wasting disk space. The …
=> chore: use nushell as a task runner
